name: zupito
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  provider: ^6.1.2
  shared_preferences: ^2.2.3
  flutter_map: ^8.1.1
  latlong2: ^0.9.1
  http: ^1.2.1
  flutter_secure_storage: ^9.2.4
  geolocator: ^14.0.2
  location: ^8.0.1
  socket_io_client: ^3.1.2

  google_sign_in: ^6.2.1 # Corrected to be compatible with SDK 3.2.6
  firebase_core: ^3.15.1
  firebase_auth: ^5.6.2

  image_picker: ^1.0.7 # Corrected to be compatible with SDK 3.2.6

  flutter_local_notifications: ^19.2.0
  flutter_paypal: ^0.2.1 # Corrected to be compatible with SDK 3.2.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0 # Corrected to be compatible with SDK 3.2.6
  flutter_native_splash: ^2.4.0
  webview_flutter: ^4.7.0

flutter_native_splash:
  color: "#ffffff"
  image: assets/images/splash.jpeg
  android: true
  ios: true
  web: false

flutter:
  uses-material-design: true
  assets:
    - assets/images/splash.png
    - assets/images/station_pin.jpg
    - assets/images/user_marker.png
