name: zupito
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  provider: ^6.0.0
  google_sign_in: ^6.1.6
  firebase_auth: ^4.17.8
  firebase_core: ^2.27.0
  flutter_map: ^6.1.0

  latlong2: ^0.9.0
  http: ^1.2.1
  flutter_secure_storage: ^8.0.0
  geolocator: ^9.0.2

  location: ^5.0.0
  qr_code_scanner:
    git:
      url: https://github.com/juliuscanute/qr_code_scanner.git
      ref: master
  flutter_local_notifications: ^19.3.0
  socket_io_client: ^2.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_native_splash: ^2.2.18

flutter_native_splash:
  color: "#ffffff"
  image: assets/images/splash.jpeg
  android: true
  ios: true
  web: false

flutter:
  uses-material-design: true
  assets:
    - assets/images/splash.png
    - assets/images/station_pin.jpg
    - assets/images/user_marker.png
