// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCc_3tDUvCjLT6qP6_7TpVGx5AoomIwMz4',
    appId: '1:805064172151:web:b7a06d6f45d394435d5c72',
    messagingSenderId: '805064172151',
    projectId: 'zupito-71a71',
    authDomain: 'zupito-71a71.firebaseapp.com',
    storageBucket: 'zupito-71a71.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD2eGecBmTI4iWdlNNkQm1mMH5LTIfQEkY',
    appId: '1:805064172151:android:65a2ba907306e6145d5c72',
    messagingSenderId: '805064172151',
    projectId: 'zupito-71a71',
    storageBucket: 'zupito-71a71.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA0_-JM-F4yriUnREUp-RLqqVWmMgFyeRo',
    appId: '1:805064172151:ios:e19993c7b50913b15d5c72',
    messagingSenderId: '805064172151',
    projectId: 'zupito-71a71',
    storageBucket: 'zupito-71a71.firebasestorage.app',
    androidClientId: '805064172151-hhs9p93s1k8clfs6fqqroe5l8cilipj3.apps.googleusercontent.com',
    iosClientId: '805064172151-1ef379a3veps3fs61npt2nm4bmngg249.apps.googleusercontent.com',
    iosBundleId: 'com.example.zupito',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA0_-JM-F4yriUnREUp-RLqqVWmMgFyeRo',
    appId: '1:805064172151:ios:e19993c7b50913b15d5c72',
    messagingSenderId: '805064172151',
    projectId: 'zupito-71a71',
    storageBucket: 'zupito-71a71.firebasestorage.app',
    androidClientId: '805064172151-hhs9p93s1k8clfs6fqqroe5l8cilipj3.apps.googleusercontent.com',
    iosClientId: '805064172151-1ef379a3veps3fs61npt2nm4bmngg249.apps.googleusercontent.com',
    iosBundleId: 'com.example.zupito',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCc_3tDUvCjLT6qP6_7TpVGx5AoomIwMz4',
    appId: '1:805064172151:web:cd813a0575d492095d5c72',
    messagingSenderId: '805064172151',
    projectId: 'zupito-71a71',
    authDomain: 'zupito-71a71.firebaseapp.com',
    storageBucket: 'zupito-71a71.firebasestorage.app',
  );
}
